// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_ultimate_racer = "CgkIz4z-5pYGEAIQBg"; // <GPGSID>
        public const string achievement_ruling_speedster = "CgkIz4z-5pYGEAIQBw"; // <GPGSID>
        public const string achievement_supreme_rider = "CgkIz4z-5pYGEAIQCA"; // <GPGSID>
        public const string achievement_fiery_accelerando = "CgkIz4z-5pYGEAIQBQ"; // <GPGSID>
        public const string achievement_game_changer = "CgkIz4z-5pYGEAIQAg"; // <GPGSID>
        public const string achievement_bike_master = "CgkIz4z-5pYGEAIQBA"; // <GPGSID>
        public const string achievement_topnotch_biker = "CgkIz4z-5pYGEAIQCg"; // <GPGSID>
        public const string achievement_racing_pro = "CgkIz4z-5pYGEAIQCQ"; // <GPGSID>
        public const string leaderboard_best_score = "CgkIz4z-5pYGEAIQAA"; // <GPGSID>
        public const string achievement_ramp_conqueror = "CgkIz4z-5pYGEAIQAw"; // <GPGSID>
        public const string achievement_amazing_tyro = "CgkIz4z-5pYGEAIQAQ"; // <GPGSID>

}

